--- 
name: "Bump version"

on:
  workflow_call:

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - 
        name: "Checkout main branch to calculate changelog"
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - 
        id: tag_version
        name: "Calculate version"
        uses: miguelfito/github-bump-and-tag-action@v1
        with: 
          create_annotated_tag: true
          default_bump: patch
          dry_run: true
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          release_branches: main
          tag_prefix: ""
      - 
        name: "Create CHANGELOG.md"
        run: "echo \"${{ steps.tag_version.outputs.changelog }}\" > CHANGELOG.md"
      - 
        name: "Commit & push CHANGELOG.md"
        uses: stefanzweifel/git-auto-commit-action@v4
        with: 
          branch: main
          commit_message: "chore(release): Automated version bumping to ${{ steps.tag_version.outputs.new_tag }}"
          commit_user_email: actions@github.com
          commit_user_name: "GitHub Actions"
          file_pattern: CHANGELOG.md
      - 
        id: updated_sha
        name: "Get updated commit SHA"
        run: "echo \"##[set-output name=commit_id;]$(git rev-parse HEAD)\"\n"
      - 
        name: "Bump version and push tag"
        uses: miguelfito/github-bump-and-tag-action@v1
        with: 
          commit_sha: "${{ steps.updated_sha.outputs.commit_id }}"
          create_annotated_tag: true
          default_bump: patch
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          release_branches: main
          tag_prefix: ""
      - 
        env: 
          GITHUB_SHA: "${{ steps.updated_sha.outputs.commit_id }}"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        name: "Create a GitHub release"
        uses: actions/create-release@v1
        with: 
          body: "${{ steps.tag_version.outputs.changelog }}"
          commitish: "${{ steps.updated_sha.outputs.commit_id }}"
          release_name: "Release ${{ steps.tag_version.outputs.new_tag }}"
          tag_name: "${{ steps.tag_version.outputs.new_tag }}"
